// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwaXeClyAvn0eeYTeY79bGqVF6ioLXNjI',
    appId: '1:617824074751:web:275b39f3b57b92df6605ca',
    messagingSenderId: '617824074751',
    projectId: 'walk-in-salon-59461',
    authDomain: 'walk-in-salon-59461.firebaseapp.com',
    storageBucket: 'walk-in-salon-59461.firebasestorage.app',
    measurementId: 'G-953ZZ6D53F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbt4XkGtsJkrf0071mpgT8t-mnUcvzigI',
    appId: '1:617824074751:android:be45285d282bb7a06605ca',
    messagingSenderId: '617824074751',
    projectId: 'walk-in-salon-59461',
    storageBucket: 'walk-in-salon-59461.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvWWKclXa_DH-GXH3gy-UxsyX6zoZ-ueE',
    appId: '1:617824074751:ios:12bdba59c3943f976605ca',
    messagingSenderId: '617824074751',
    projectId: 'walk-in-salon-59461',
    storageBucket: 'walk-in-salon-59461.firebasestorage.app',
    iosBundleId: 'com.example.walkinsalonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvWWKclXa_DH-GXH3gy-UxsyX6zoZ-ueE',
    appId: '1:617824074751:ios:12bdba59c3943f976605ca',
    messagingSenderId: '617824074751',
    projectId: 'walk-in-salon-59461',
    storageBucket: 'walk-in-salon-59461.firebasestorage.app',
    iosBundleId: 'com.example.walkinsalonapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwaXeClyAvn0eeYTeY79bGqVF6ioLXNjI',
    appId: '1:617824074751:web:132f3b1192829c746605ca',
    messagingSenderId: '617824074751',
    projectId: 'walk-in-salon-59461',
    authDomain: 'walk-in-salon-59461.firebaseapp.com',
    storageBucket: 'walk-in-salon-59461.firebasestorage.app',
    measurementId: 'G-EZGXSHN67X',
  );
}
